[package]
name = "utoipauto-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
tokio = "1.36.0"
utoipa = { version = "4.1.0", features = ["axum_extras"] }
utoipauto = "0.1.9"
